// Collateral Vault IDL
// This IDL is auto-generated by Anchor - do not edit manually
import collateralVaultIdlJson from "./collateral-vault-idl.json";
import { Idl } from "@coral-xyz/anchor";

export const collateralVaultIdl: Idl = collateralVaultIdlJson as Idl;
